name: encrypt
version: 0.2.0
description: A set of high-level APIs over PointyCastle for two-way cryptography.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/encrypt

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  pointycastle: ^1.0.0-rc2

dev_dependencies:
  test: ^1.3.0
